server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php index.html;

    # Optimasi Gzip agar transfer data lebih kecil & kencang
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Direct access ke folder uploads (PAKAI LOCATION ~* agar lebih cepat)
    location /uploads/ {
        alias /var/www/html/writable/uploads/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
        access_log off;
    }

    # Optimasi untuk aset CSS, JS, dan Images di folder public
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
        access_log off;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass undangan_pernikahan_app:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
        
        # Tambahan Buffer agar PHP-FPM lebih stabil
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
    }

    # Blokir akses ke file sensitif
    location ~ /\. {
        deny all;
    }
}