server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # Folder utama aplikasi
    root   /usr/share/nginx/html;
    index  index.html index.htm index.php;

    # Log untuk mempermudah debugging jika ada Error 502/404
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    # Mengatur Gzip agar loading web lebih ringan/cepat
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    location / {
        # Sangat penting untuk React/SPA/CI4/Laravel agar routing tidak 404 saat di-reload
        try_files $uri $uri/ /index.html /index.php?$query_string;
    }

    # Optimasi Assets (CSS, JS, Images)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
        access_log off; # Matikan log untuk assets agar file log tidak cepat penuh
    }

    # Melindungi file sensitif agar tidak bisa diakses publik (seperti .env atau .git)
    location ~ /\.(?!well-known).* {
        deny all;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}